### PR TITLE
[add] CI trigger flexibility

### PR DESCRIPTION
**Pull request by lpascal-ledger**
Adding CI trigger for convenience, so that PRs on external repos do embed CI status

### CODE REVIEW

**Comment by lpascal-ledger** [comment]
Would improve visibility on PR such as [this one](https://github.com/LedgerHQ/app-oasis/pull/5). Thanks!

**Comment by jleni** [comment]
Thanks @lpascal-ledger ! 
We will progressively add this to all other repos we manage!

**Review by ftheirs — APPROVED** [review]

**Review by ftheirs — COMMENTED** [review]
It seems good to me but we need to bump version before merging it

**Comment by tjanez** [comment]
> It seems good to me but we need to bump version before merging it

The thing is that Ledger already released version 2.3.2 of the Oasis app based on https://github.com/LedgerHQ/app-oasis/pull/5 so I think it would make more sense to try to merge that PR (and this one) without bumping the version?

**Comment by jleni** [comment]
ok, let's merge without a new version to avoid any confusion

**Pull request merged**
